global:
  imagePullSecret: {}

# SAP Alert Notification Service 
alert_notification:
  fullnameOverride: alert-notification
  serviceOfferingName: alert-notification
  servicePlanName: lite #free
  parameters:
    configuration:
      actions:
      - name: send-email
        properties:
          destination: mio.fujita.01@gmail.com
        state: ENABLED
        type: EMAIL
      conditions:
      - name: Alert-App-Generic
        predicate: EQUALS
        propertyKey: eventType
        propertyValue: alert.app.generic
      subscriptions:
      - actions:
        - send-email
        conditions:
        - Alert-App-Generic
        name: App-Alerts
        state: ENABLED
